services:
  fail2ban:
    image: crazymax/fail2ban:latest
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO
      - IPTABLES_MODE=auto
    volumes:
      - ./fail2ban:/data
      - /var/log/caddy:/var/log/caddy:ro