services:
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./fail2ban-config:/config
      - /var/log:/var/log:ro
