services:
  gateway:
    image: dariomr8/apigw:latest
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "127.0.0.1:8080:8080"  # expose only to host, not public
    depends_on:
      - lab-home
      - redis
      - api-stress-test
      - ichiro-family-tree
      - shortly
      - ichiro-walks