services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    command:
      - --http-enabled                    # keep HTTP internally
      - --base-url
      - /portainer                        # match spring gateway configuration
      - --trusted-origins
      - dariolab.com,www.dariolab.com
    expose:
      - "9000"
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    security_opt:
      - no-new-privileges:true