services:
  loki:
    image: grafana/loki:2.9.4
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    networks: [ backend ]

  promtail:
    image: grafana/promtail:2.9.4
    restart: unless-stopped
    command:
      - -config.file=/etc/promtail/config.yml
      - -config.expand-env=true
    environment:
      PROMTAIL_HOST_LABEL: ${PROMTAIL_HOST_LABEL}
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - /var/log/caddy:/var/log/caddy:ro
      - promtail_pos:/var/lib/promtail
    networks: [ backend ]
    depends_on: [ loki ]

  grafana:
    image: grafana/grafana:10.4.5
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SERVER_ROOT_URL: ${GRAFANA_SERVER_ROOT}
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    networks: [ backend ]
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
