services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    image: caddy-with-ratelimit:2.10.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - /var/log/caddy:/var/log/caddy
    networks:
      - backend
    depends_on:
      - gateway