name: dariolab

include:
  - compose.caddy.yml
  - compose.watchtower.yml
  - compose.portainer.yml
  - compose.gateway.yml
  - compose.apps.yml

networks:
  backend:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  portainer_data:
