services:
  caddy:
    image: caddy:2.10.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend
    depends_on:
      - gateway

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 300
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: dario.mauri9@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: dario.mauri9@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: dario.mauri9@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "${EMAIL_SERVER_PASSWORD}"

  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - backend

  gateway:
    image: dariomr8/apigw:latest
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "127.0.0.1:8080:8080"  # expose only to host, not public
    depends_on:
      - lab-home
      - redis
      - api-stress-test
      - ichiro-family-tree
      - shortly
      - ichiro-walks

  lab-home:
    image: dariomr8/lab-home:latest
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - backend

  api-stress-test:
    image: dariomr8/api-stress-test:latest
    restart: unless-stopped
    expose:
      - "8083"
    networks:
      - backend
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
      ENCRYPTION_KEY: "${ENCRYPTION_KEY}"

  ichiro-family-tree:
    image: dariomr8/ichiro:latest
    restart: unless-stopped
    expose:
      - "8081"
    networks:
      - backend
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"

  shortly:
    image: dariomr8/shortly:latest
    restart: unless-stopped
    expose:
      - "8082"
    networks:
      - backend
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"

  ichiro-walks:
    image: dariomr8/ichiro-walks:latest
    restart: unless-stopped
    expose:
      - "8085"
    networks:
      - backend
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"

networks:
  backend:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
