services:
  gateway:
    image: dariomr8/apigw:latest
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "127.0.0.1:8080:8080"  # expose only to host, not public
    depends_on:
      - redis
      - api-stress-test
      - ichiro-family-tree

  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - backend

  api-stress-test:
    image: dariomr8/api-stress-test:latest
    restart: unless-stopped
    expose:
      - "8083"
    networks:
      - backend
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
      ENCRYPTION_KEY: "${ENCRYPTION_KEY}"

  ichiro-family-tree:
    image: dariomr8/ichiro:latest
    restart: unless-stopped
    expose:
      - "8081"
    networks:
      - backend
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"

networks:
  backend:
    driver: bridge
