spring:
  cloud:
    gateway.server.webflux:
      routes:
        - id: lab-home
          order: 100
          uri: http://localhost:80
          predicates:
            - Path=/, /index.html, /assets/**, /icons/**, /favicon.ico

        - id: api-stress-test
          uri: http://localhost:8083
          predicates:
            - Path=/api-stress-test/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /api-stress-test

        - id: ichiro-family-tree
          uri: http://localhost:8081
          predicates:
            - Path=/ichiro-family-tree/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /ichiro-family-tree

        - id: shortly
          uri: http://localhost:8082
          predicates:
            - Path=/shortly/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /shortly

        - id: ichiro-walks
          uri: http://localhost:8085
          predicates:
            - Path=/ichiro-walks/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /ichiro-walks

        - id: portainer
          uri: http://localhost:9000
          predicates:
            - Path=/portainer/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /portainer

        - id: grafana
          uri: http://localhost:3000
          predicates:
            - Path=/grafana/**
          filters:
            - AddRequestHeader=X-Forwarded-Prefix, /grafana
            - PreserveHostHeader
