spring:
  cloud:
    gateway.server.webflux:
      routes:
        - id: api-stress-test
          uri: http://localhost:8083
          predicates:
            - Path=/api-stress-test/**
          filters:
            - name: PrefixAwareForwardingFilter
              args:
                prefix: /api-stress-test

        - id: ichiro-family-tree
          uri: http://localhost:8081
          predicates:
            - Path=/ichiro-family-tree/**
          filters:
            - name: PrefixAwareForwardingFilter
              args:
                prefix: /ichiro-family-tree

        - id: shortly
          uri: http://localhost:8082
          predicates:
            - Path=/shortly/**
          filters:
            - name: PrefixAwareForwardingFilter
              args:
                prefix: /shortly

        - id: ichiro-walks
          uri: http://localhost:8085
          predicates:
            - Path=/ichiro-walks/**
          filters:
            - name: PrefixAwareForwardingFilter
              args:
                prefix: /ichiro-walks
