server:
  http_listen_port: 0
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /var/lib/promtail/positions.yaml

scrape_configs:
  - job_name: caddy_access
    static_configs:
      - targets: [ localhost ]
        labels:
          job: caddy_access
          host: ${PROMTAIL_HOST_LABEL}
          __path__: /var/log/caddy/access.log
    pipeline_stages:
      - json:
          expressions:
            ts:
            level:
            logger:
            msg:
            request:
            status:
            size:
            duration:
      - json:
          source: request
          expressions:
            remote_ip:
            uri:
            method:
      - geoip:
          db: /etc/promtail/GeoLite2-City.mmdb
          source: remote_ip
          db_type: city
    relabel_configs:
      - action: labelkeep
        regex: job|host|geoip_country_name|geoip_country_code
      - action: labeldrop
        regex: filename
